#!/bin/bash

# Get input arguments
if [ "$#" -ne 1 ]; then
    echo "Usage: ec2start <instance-name>"
    exit 0
fi
NAME=$1

# Find instance ID from Tag name
INSTANCE_ID=`aws ec2 describe-instances --filters "Name=tag:Name,Values=${NAME}" | jq -r '.Reservations[0].Instances[0].InstanceId'`
if [ $INSTANCE_ID == null ]
then
    echo "No instance found with name '${NAME}'"
    exit 0
fi

# Check if already running
STATE=`aws ec2 describe-instances --filters "Name=tag:Name,Values=${NAME}" | jq -r '.Reservations[0].Instances[0].State.Name'`
if [ "$STATE" == "running" ]
then
    echo "EC2 instance ${NAME} (${INSTANCE_ID}) is already started ..."
    exit 0
fi

# To avoid unwanted behavior, we only allow starting an instance from a 'stopped' state
if [ "$STATE" != "stopped" ]
then
    echo "EC2 instance ${NAME} (${INSTANCE_ID}) is not in 'stopped' state, please check the web console"
    exit 0
fi

echo "Starting EC2 instance ${NAME} (${INSTANCE_ID}) ..."
aws ec2 start-instances --instance-ids $INSTANCE_ID | jq
echo "Started ... give it a couple of minutes for the machine to be fully booted"
